"""Monthly low-confidence audit over public/data/sensors.json + phones.json.

Lists Low/Medium/unverified sensors and phone-camera mappings, mappings and sensors
without a source URL, and sensors missing core specs. Writes
data/reports/<date>-audit.md and .json. Read-only with respect to the database.
"""
from __future__ import annotations

import argparse
import json
from collections import Counter
from urllib.parse import urlsplit

from common import REPORTS_DIR, ROOT, today, utc_now

SENSORS_JSON = ROOT / 'public' / 'data' / 'sensors.json'
PHONES_JSON = ROOT / 'public' / 'data' / 'phones.json'
LOW = {'low', 'medium', 'unverified', ''}


def is_low(confidence) -> bool:
    return (confidence or '').strip().lower() in LOW


def host(url: str | None) -> str:
    return urlsplit(url).netloc if url else ''


def run_audit() -> dict:
    sensors = json.loads(SENSORS_JSON.read_text(encoding='utf-8'))
    phones = json.loads(PHONES_JSON.read_text(encoding='utf-8'))

    low_sensors, sensors_no_source, missing_specs = [], [], []
    for s in sensors:
        urls = [s.get('source_url')] + [x.get('url') for x in s.get('sources') or []]
        urls = [u for u in urls if u]
        row = {'canonical_id': s['canonical_id'], 'manufacturer': s.get('manufacturer'),
               'confidence': s.get('confidence'), 'phone_count': s.get('phone_count') or 0,
               'source_hosts': sorted({host(u) for u in urls})}
        if is_low(s.get('confidence')):
            low_sensors.append(row)
        if not urls:
            sensors_no_source.append(row)
        missing = [f for f in ('resolution_mp', 'pixel_size_um', 'sensor_size') if s.get(f) in (None, '')]
        if missing:
            missing_specs.append({**row, 'missing': missing})

    low_mappings, mappings_no_source = [], []
    for p in phones:
        for cam in p.get('cameras') or []:
            row = {'phone': p['canonical_id'], 'model': p.get('model'), 'sensor_id': cam.get('sensor_id'),
                   'role': cam.get('role'), 'confidence': cam.get('confidence'), 'source_url': cam.get('source_url')}
            if is_low(cam.get('confidence')):
                low_mappings.append(row)
            if not cam.get('source_url'):
                mappings_no_source.append(row)

    low_sensors.sort(key=lambda r: (-r['phone_count'], r['canonical_id']))
    low_mappings.sort(key=lambda r: (r['confidence'] or '', r['phone']))
    return {
        'date': today(),
        'generated_at': utc_now(),
        'confidence_distribution': {
            'sensors': dict(Counter(s.get('confidence') or '(blank)' for s in sensors)),
            'mappings': dict(Counter(c.get('confidence') or '(blank)' for p in phones for c in p.get('cameras') or [])),
        },
        'summary': {
            'sensors': len(sensors), 'low_confidence_sensors': len(low_sensors),
            'sensors_without_source': len(sensors_no_source), 'sensors_missing_core_specs': len(missing_specs),
            'mappings': sum(len(p.get('cameras') or []) for p in phones),
            'low_confidence_mappings': len(low_mappings), 'mappings_without_source': len(mappings_no_source),
        },
        'low_confidence_sensors': low_sensors,
        'sensors_without_source': sensors_no_source,
        'sensors_missing_core_specs': missing_specs,
        'low_confidence_mappings': low_mappings,
        'mappings_without_source': mappings_no_source,
    }


def summary_lines(audit: dict) -> list[str]:
    s = audit['summary']
    return [
        f"- Sensors: {s['sensors']}; Low/Medium/unverified: **{s['low_confidence_sensors']}**; "
        f"without source URL: {s['sensors_without_source']}; missing core specs: {s['sensors_missing_core_specs']}",
        f"- Phone-camera mappings: {s['mappings']}; Low/Medium/unverified: **{s['low_confidence_mappings']}**; "
        f"without source URL: {s['mappings_without_source']}",
        f"- Sensor confidence: {audit['confidence_distribution']['sensors']}",
        f"- Mapping confidence: {audit['confidence_distribution']['mappings']}",
    ]


def _table(rows, cols, max_rows):
    if not rows:
        return ['_None._', '']
    out = ['| ' + ' | '.join(h for h, _ in cols) + ' |', '|' + '---|' * len(cols)]
    for r in rows[:max_rows]:
        vals = [r.get(k) for _, k in cols]
        out.append('| ' + ' | '.join((', '.join(v) if isinstance(v, list) else str(v if v is not None else ''))
                                     .replace('|', '\\|') for v in vals) + ' |')
    if len(rows) > max_rows:
        out.append(f'\n_{len(rows) - max_rows} more rows in the JSON sidecar._')
    return out + ['']


def render_markdown(audit: dict, max_rows: int) -> str:
    md = [f"# Low-confidence audit ({audit['date']})", '',
          'Generated by `scripts/collect/audit_low_confidence.py`. Re-check these against official sources; '
          'upgrade confidence only with a new source URL.', '']
    md += summary_lines(audit) + ['']
    md += ['## Low/Medium confidence sensors (most-used first)', '']
    md += _table(audit['low_confidence_sensors'], [('Sensor', 'canonical_id'), ('Maker', 'manufacturer'),
                                                   ('Confidence', 'confidence'), ('Phones', 'phone_count'),
                                                   ('Source hosts', 'source_hosts')], max_rows)
    md += ['## Low/Medium confidence phone mappings', '']
    md += _table(audit['low_confidence_mappings'], [('Phone', 'model'), ('Sensor', 'sensor_id'), ('Role', 'role'),
                                                    ('Confidence', 'confidence'), ('Source', 'source_url')], max_rows)
    md += ['## Mappings without source URL', '']
    md += _table(audit['mappings_without_source'], [('Phone', 'model'), ('Sensor', 'sensor_id'), ('Role', 'role'),
                                                     ('Confidence', 'confidence')], max_rows)
    md += ['## Sensors without source URL', '']
    md += _table(audit['sensors_without_source'], [('Sensor', 'canonical_id'), ('Confidence', 'confidence')], max_rows)
    md += ['## Sensors missing core specs', '']
    md += _table(audit['sensors_missing_core_specs'], [('Sensor', 'canonical_id'), ('Missing', 'missing'),
                                                       ('Confidence', 'confidence')], max_rows)
    return '\n'.join(md)


def write_audit(audit: dict, max_rows: int = 500):
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    stem = REPORTS_DIR / f"{audit['date']}-audit"
    md_path, json_path = stem.with_suffix('.md'), stem.with_suffix('.json')
    md_path.write_text(render_markdown(audit, max_rows) + '\n', encoding='utf-8')
    json_path.write_text(json.dumps(audit, ensure_ascii=False, indent=1) + '\n', encoding='utf-8')
    return md_path, json_path


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--max-rows', type=int, default=500)
    parser.add_argument('--date', help='report date (default: today UTC)')
    args = parser.parse_args(argv)
    audit = run_audit()
    if args.date:
        audit['date'] = args.date
    md_path, _ = write_audit(audit, args.max_rows)
    print(f"audit: {json.dumps(audit['summary'])} -> {md_path.relative_to(ROOT).as_posix()}")
    return audit


if __name__ == '__main__':
    main()
